### ISSUE TITLE
Require Whoops in FuelPHP

### ISSUE THREAD

**Issue by tjapro** [indigophp/fuel-whoops#1]
Hello!
I've tried to require whoops in FuePHP composer.json

```
    "require": {
        "php": ">=5.3.3",
        "composer/installers": "~1.0",
        "fuel/docs": "dev-1.7/master",
        "fuel/core": "dev-1.7/master",
        "fuel/auth": "dev-1.7/master",
        "fuel/email": "dev-1.7/master",
        "fuel/oil": "dev-1.7/master",
        "fuel/orm": "dev-1.7/master",
        "fuel/parser": "dev-1.7/master",
        "fuelphp/upload": "2.0.2",
        "monolog/monolog": "1.5.*",
        "michelf/php-markdown": "1.4.0",
        "indigophp/fuel-whoops": "@stable"
    },
```

But when I do composer update, it says to me:
`Problem 1
    - The requested package indigophp/fuel-whoops could not be found in any version, there may be a typo in the package name.`

Now, what can I do?
Thanks.

**Comment by sagikazarmark** [comment]
Hi,

This is because this package never made it to be stable. Try `dev-develop` constraint.

**Comment by tjapro** [comment]
Ok, I understand. But if the package is in development, it isn't stable to use, it is?

**Comment by sagikazarmark** [comment]
To be honest, I kind of stopped developping this package. I used it in production in tha past.

**Comment by tjapro** [comment]
So, I think there is a better error handler for PHP...
I'll search in the net, but can you suggest me one?
Thanks.

**Comment by sagikazarmark** [comment]
Try BooBoo from the PHP League

**Comment by tjapro** [comment]
Very thank you!
The PHP League is a website with many interesting things fo PHP.
I'll read more about this BooBoo.
Thanks again.
